name: deployment 

on:
  push:
    branches: [main]


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
        
      - name: install modules
        run: npm ci
      
      - name: build
        run: npm run build
